### ISSUE TITLE
Change everything to use https

### ISSUE THREAD

**Issue by alexjbest** [pbelmans/topologies-comparison#7]
Seeing as pbelmans.ncag.info supports https my browser tries to load that by default which breaks all scripts and fonts loaded over http, this applies to some of your other interacts too.
The recommended fix is to change all scripts to load over https which works fine even if a user does not connect to the site over https.

I can force my browser to use http but I thought I'd mention it as it can be confusing why nothing works!

Thanks.

**Comment by pbelmans** [comment]
Oh, great for telling me this. I had [this page](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) bookmarked to set things straight at some point, but I obviously haven't so far. I'll set things to HTTPS by default, *and* check all these interactive scripts.

**Comment by pbelmans** [comment]
Everything should now work over https. Please let me know if I forgot something. Thanks for telling me!
