### ISSUE TITLE
Mistakes in proper topology and envelope topology

### ISSUE THREAD

**Issue by Alizter** [pbelmans/topologies-comparison#9]
Quoting [arXiv:1407.5782](https://arxiv.org/abs/1407.5782):

The proper topology (or prop) is generated by families (5) which are jointly surjective and such that each fi is a proper morphism.

The envelope topology (or cdp) is generated by completely decomposed families (5) with each fi a proper morphism

Currently cdp: a surjective singleton family {f:Y→X}i∈I, for f a proper morphism
and prop: a completely decomposed singleton family {f:Y→X}i∈I, for f a proper morphism

Which seem to be way off.

**Comment by pbelmans** [comment]
Many thanks for pointing this out, and apologies for the slow fix. I also noticed an issue with the graph (I really messed things up all those years ago), now it is verbatim the graph from Gabber--Kelly (except that I've added smooth and syntomic).
